/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aerolinea.presentacion.check_in;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import javax.imageio.ImageIO;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author pc
 */
public class View extends javax.swing.JInternalFrame implements Observer {

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
        this.model.addObserver(this);
    }

    public Controller getController() {
        return controller;
    }

    /**
     * Creates new form View
     */
    public void setController(Controller controller) {
        this.controller = controller;
    }

    public View() {
        initComponents();
        this.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                change(e.getX(), e.getY());
            }
        });
        try {
            NON_AVAILABLE_SEAT = ImageIO.read(getClass().getResourceAsStream(NON_AVAILABLE_SEAT_PATH));
            AVAILABLE_SEAT = ImageIO.read(getClass().getResourceAsStream(AVAILABLE_SEAT_PATH));
        } catch (IOException ex) {

        }
        this.jTableSeat.setLocation(BEGIN, BEGIN);
        this.jTableSeat.getTableHeader().setReorderingAllowed(false);
        this.jTableSeat.getTableHeader().setResizingAllowed(false);
        this.jTableSeat.setOpaque(false);
        ((DefaultTableCellRenderer) this.jTableSeat.getDefaultRenderer(Object.class)).setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSeat = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTableSeat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSeatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSeat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void jTableSeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSeatMouseClicked
        if (evt.getClickCount() == 2) {
            this.change(this.jTableSeat.getSelectedColumn(), this.jTableSeat.getSelectedRow());
        }
    }//GEN-LAST:event_jTableSeatMouseClicked

    private Model model;
    private Controller controller;

    @Override
    public void update(java.awt.Graphics g) {
        this.paint(g);
    }

    @Override
    public void update(Observable o, Object arg) {
        this.repaint();
        this.jTableSeat.setOpaque(false);
        this.jTableSeat.setRowHeight(AVAILABLE_SEAT.getHeight(this) + AVAILABLE_SEAT.getHeight(this) / 4);
    }

    @Override
    public void paint(java.awt.Graphics g) {
        super.paint(g);
        this.renderRowIndex(g);
    }

    @Override
    public void setVisible(boolean isVisible) {
        if (isVisible) {
            this.jTableSeat.setModel(new SeatTableModel(this.model.getArray()));
        }
        super.setVisible(isVisible);
    }

    private void renderRowIndex(java.awt.Graphics g) {
        int xPosition = BEGIN - this.jTableSeat.getColumnModel().getColumn(0).getWidth() - WIDTH;
        int yPosition = BEGIN + this.jTableSeat.getRowHeight();
        int uCode = UFIRST;
        for (int x = 0; x < this.model.getArray().getColumn(); x++) {
            g.drawString(Character.toString((char) uCode++), xPosition, yPosition);
            yPosition += this.jTableSeat.getRowHeight();
        }
//        xPosition = BEGIN + AVAILABLE_SEAT.getWidth(this) / 4;
//        yPosition = BEGIN - WIDTH;
//        for (int y = 0; y < this.model.getArray().getRow(); y++) {
//            g.drawString(Integer.toString(y), xPosition, yPosition);
//            xPosition += X_DISTANCE;
//        }
//        xPosition = BEGIN;
//        yPosition = BEGIN;
//        for (int i = 0; i < this.model.getArray().getColumn(); i++) {
//            for (int z = 0; z < this.model.getArray().getRow(); z++) {
//                g.drawImage(
//                        (this.model.getArray().get(z, i)
//                        ? AVAILABLE_SEAT
//                        : NON_AVAILABLE_SEAT), xPosition, yPosition, this);
////                g.setColor((this.model.getArray().get(z, i) ? Color.RED : Color.BLUE));
////                g.fillRect(xPosition, yPosition, WIDTH, WIDTH);
//                xPosition += X_DISTANCE;
//            }
//            xPosition = BEGIN;
//            yPosition += Y_DISTANCE;
//        }
    }

    private void change(int x, int y) {
        this.controller.changeFlag(x, y);
    }
    private static final int BEGIN = 100;
    private static final int WIDTH = 10;
    private static final int Y_DISTANCE = 24;
    private static final int X_DISTANCE = 24;
    private static final int UFIRST = 0x41;
    private static Image AVAILABLE_SEAT;
    private static Image NON_AVAILABLE_SEAT;
    private static final String AVAILABLE_SEAT_PATH = "../recursos/available.png";
    private static final String NON_AVAILABLE_SEAT_PATH = "../recursos/nonavailable.png";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSeat;
    // End of variables declaration//GEN-END:variables
}
