/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aerolinea.presentacion.vuelos.edicion;

import aerolinea.logica.Avion;
import aerolinea.logica.Ciudad;
import java.sql.Time;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author pc
 */
public class View extends javax.swing.JInternalFrame implements Observer {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelDia = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelOrigen = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabelAvion = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jComboBoxHora = new javax.swing.JComboBox<>();
        jComboBoxMinuto = new javax.swing.JComboBox<>();
        jComboBoxSegundo = new javax.swing.JComboBox<>();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jComboBoxAvion = new javax.swing.JComboBox<>();
        jLabelMinuto = new javax.swing.JLabel();
        jLabelSegundo = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jLabelTitulo.setText("Edición de vuelo");

        jLabelID.setText("ID");

        jLabelDia.setText("Día");

        jLabelHora.setText("Hora");

        jLabelOrigen.setText("Origen");

        jLabelDestino.setText("Destino");

        jLabelAvion.setText("Avión");

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jComboBoxHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHoraActionPerformed(evt);
            }
        });

        jLabelMinuto.setText("Minuto");

        jLabelSegundo.setText("Segundo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelID)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDia)
                                    .addComponent(jLabelOrigen)
                                    .addComponent(jLabelDestino)
                                    .addComponent(jLabelAvion))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonAgregar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonConsultar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonModificar))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBoxOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldID))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelHora)
                                .addGap(34, 34, 34)
                                .addComponent(jComboBoxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMinuto)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSegundo)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(80, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelID)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDia)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHora)
                            .addComponent(jLabelMinuto)
                            .addComponent(jLabelSegundo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrigen)
                    .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDestino)
                    .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAvion)
                    .addComponent(jComboBoxAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButtonModificar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHoraActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        this.controller.agregar(this.toVuelo());
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        this.controller.consultar(this.jTextFieldID.getText());
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        this.controller.modificar(this.toVuelo());
    }//GEN-LAST:event_jButtonModificarActionPerformed
    public Model model;
    public Controller controller;

    @Override
    public void update(Observable o, Object arg) {
        this.renderVuelo(this.model.getVuelo());
    }

    private void renderVuelo(aerolinea.logica.Vuelo v) {
        this.jTextFieldID.setText(v.getIdVuelo());
        // Combo
        // Avión
        this.jComboBoxAvion.setModel(new DefaultComboBoxModel<Avion>(
                this.model.getAviones().toArray(new Avion[0])));
        this.jComboBoxAvion.setSelectedItem(v.getAvion());
        // Origen
        this.jComboBoxOrigen.setModel(new DefaultComboBoxModel<Ciudad>(
                this.model.getCiudades().toArray(new Ciudad[0])));
        this.jComboBoxOrigen.setSelectedItem(v.getOrigen());
        // Destino
        this.jComboBoxDestino.setModel(new DefaultComboBoxModel<Ciudad>(
                this.model.getCiudades().toArray(new Ciudad[0])));
        this.jComboBoxDestino.setSelectedItem(v.getDestino());
        // Día
        this.jComboBoxDia.setModel(new DefaultComboBoxModel<String>(
                this.model.getDias().toArray(new String[0])));
        this.jComboBoxDia.setSelectedItem(v.getDia());
        // TIME
        // Hora
        this.jComboBoxHora.setModel(new DefaultComboBoxModel<Integer>(
                this.model.getHora().toArray(new Integer[0])));
        this.jComboBoxHora.setSelectedItem(v.getHora().getHours());
        // Minuto
        this.jComboBoxMinuto.setModel(new DefaultComboBoxModel<Integer>(
                this.model.getMinuto().toArray(new Integer[0])));
        this.jComboBoxMinuto.setSelectedItem(v.getHora().getMinutes());
        // Segundo
        this.jComboBoxSegundo.setModel(new DefaultComboBoxModel<Integer>(
                this.model.getSegundo().toArray(new Integer[0])));
        this.jComboBoxSegundo.setSelectedItem(v.getHora().getSeconds());

    }

    private aerolinea.logica.Vuelo toVuelo() {
        aerolinea.logica.Vuelo nuevo = new aerolinea.logica.Vuelo();
        nuevo.setIdVuelo(this.jTextFieldID.getText());
        nuevo.setOrigen((Ciudad) this.jComboBoxOrigen.getSelectedItem());
        nuevo.setDestino((Ciudad) this.jComboBoxDestino.getSelectedItem());
        nuevo.setAvion((Avion) this.jComboBoxAvion.getSelectedItem());
        nuevo.setDia((String) this.jComboBoxDia.getSelectedItem());
        // TIME
        nuevo.setHora(this.toSQLTime());
        return nuevo;
    }

    private Time toSQLTime(){
        Time nuevo = new Time(
                this.jComboBoxHora.getSelectedIndex(),
                this.jComboBoxMinuto.getSelectedIndex(),
                this.jComboBoxSegundo.getSelectedIndex());
        return nuevo;
    }
    
    public Model getModel() {
        return this.model;
    }

    public void setModel(Model model) {
        this.model = model;
        this.model.addObserver(this);
    }

    public Controller getController() {
        return controller;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<Avion> jComboBoxAvion;
    private javax.swing.JComboBox<Ciudad> jComboBoxDestino;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JComboBox<Integer> jComboBoxHora;
    private javax.swing.JComboBox<Integer> jComboBoxMinuto;
    private javax.swing.JComboBox<Ciudad> jComboBoxOrigen;
    private javax.swing.JComboBox<Integer> jComboBoxSegundo;
    private javax.swing.JLabel jLabelAvion;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelMinuto;
    private javax.swing.JLabel jLabelOrigen;
    private javax.swing.JLabel jLabelSegundo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
