/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aerolinea.presentacion.vuelo.listado;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author pc
 */
public class View extends javax.swing.JInternalFrame implements Observer {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuTabla = new javax.swing.JPopupMenu();
        jMenuItemEditarPop = new javax.swing.JMenuItem();
        jMenuItemActualizarPop = new javax.swing.JMenuItem();
        jMenuItemEliminarPop = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVuelos = new javax.swing.JTable();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();

        jPopupMenuTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuItemEditarPop.setText("Editar");
        jMenuItemEditarPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarPopActionPerformed(evt);
            }
        });
        jPopupMenuTabla.add(jMenuItemEditarPop);

        jMenuItemActualizarPop.setText("Actualizar");
        jPopupMenuTabla.add(jMenuItemActualizarPop);

        jMenuItemEliminarPop.setText("Eliminar");
        jMenuItemEliminarPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarPopActionPerformed(evt);
            }
        });
        jPopupMenuTabla.add(jMenuItemEliminarPop);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jTableVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableVuelos.setComponentPopupMenu(jPopupMenuTabla);
        jTableVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVuelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVuelos);

        jLabelTitulo.setText("Listado de vuelos");

        jButtonBuscar.setText("Buscar por id");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo)
                            .addComponent(jButtonBuscar)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        this.controller.buscar(this.jTextFieldID.getText());
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVuelosMouseClicked
        if (evt.getClickCount() == 2) {
            this.controller.editar(this.jTableVuelos.getSelectedRow());
        }
    }//GEN-LAST:event_jTableVuelosMouseClicked

    private void jMenuItemEliminarPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarPopActionPerformed
        this.controller.eliminar(this.jTableVuelos.getSelectedRow());
    }//GEN-LAST:event_jMenuItemEliminarPopActionPerformed

    private void jMenuItemEditarPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarPopActionPerformed
        this.controller.editar(this.jTableVuelos.getSelectedRow());
    }//GEN-LAST:event_jMenuItemEditarPopActionPerformed

    public Model model;
    public Controller controller;
    
    public Model getModel() {
        return model;
    }
    
    public void setModel(Model model) {
        this.model = model;
        this.model.addObserver(this);
    }
    
    public Controller getController() {
        return controller;
    }
    
    public void setController(Controller controller) {
        this.controller = controller;
    }
    
    @Override
    public void update(Observable o, Object arg) {
        this.jTableVuelos.setModel(new VueloTableModel(this.model.getVuelos()));
        this.jTableVuelos.getColumnModel().getColumn(0).setPreferredWidth(20);
        this.jTableVuelos.getColumnModel().getColumn(1).setPreferredWidth(30);
        this.jTableVuelos.getColumnModel().getColumn(2).setPreferredWidth(25);
        this.jTableVuelos.getColumnModel().getColumn(3).setPreferredWidth(100);
        this.jTableVuelos.getColumnModel().getColumn(5).setPreferredWidth(100);
        this.jTableVuelos.setRowHeight(50);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenuItem jMenuItemActualizarPop;
    private javax.swing.JMenuItem jMenuItemEditarPop;
    private javax.swing.JMenuItem jMenuItemEliminarPop;
    private javax.swing.JPopupMenu jPopupMenuTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVuelos;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
